# Generated by Django 5.2.4 on 2025-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('em_andamento', 'Em andamento'), ('pendente', 'Pendente')], default='pendente', verbose_name='Status'),
        ),
    ]
