# Generated by Django 5.2.4 on 2025-07-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tarefa_nome_alter_tarefa_prazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Concluído', 'Concluído'), ('Em andamento', 'Em andamento'), ('Pendente', 'Pendente')], default='Pendente', verbose_name='Status'),
        ),
    ]
