# Generated by Django 5.2.4 on 2025-07-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('copyright', models.CharField(max_length=50)),
                ('banner', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagem/')),
                ('texto', models.CharField(max_length=2000)),
                ('titulo', models.CharField(max_length=50)),
                ('data_publicacao', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Postagens',
            },
        ),
    ]
