# Generated by Django 5.2.4 on 2025-07-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='banner',
        ),
    ]
