# Generated by Django 5.2.4 on 2025-08-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data_publicacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=models.TextField(),
        ),
    ]
