# Generated by Django 5.2.4 on 2025-07-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subtitulo',
        ),
    ]
