# Generated by Django 5.2.4 on 2025-07-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subtitulo',
        ),
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
