# Generated by Django 5.2.4 on 2025-07-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_subtitulo_alter_postagem_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='copyright',
            field=models.CharField(max_length=100),
        ),
    ]
