# Generated by Django 5.2.4 on 2025-08-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data_publicacao',
            field=models.DateField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=models.CharField(),
        ),
    ]
